---

# main task to backup appliance firmware
- name: Swap active partition of appliance firmware
  ibm.isam.isam:
    log: "{{ log_level | default(omit) }}"
    force: "{{ force | default(omit) }}"
    action: ibmsecurity.isam.base.firmware.swap
