---

# main task to import signer certificates
#   Example:
#      signer_certificates:
#         -   kdb_id: "{{ item.kdb_id }}"
#             cert: "{{ inventory_dir }}/{{ item.cert  }}"
#             label: "{{ item.label }}"
---
- name: Import signer certificates
  ibm.isam.isam:
    log: "{{ log_level | default(omit) }}"
    force: "{{ force | default(omit) }}"
    action: ibmsecurity.isam.base.ssl_certificates.signer_certificate.import_cert
    isamapi:
      kdb_id: "{{ item.kdb_id }}"
      cert: "{{ inventory_dir }}/{{ item.cert  }}"
      label: "{{ item.label }}"
  with_items: "{{ signer_certificates }}"
  notify: Commit Changes
