---

# default password of uncofigured appliances
# Override this setting e.g. if pre-configured docker environment with different default password is used
first_steps_default_password: admin

# default isam ansible port for use in uri module
ansible_isam_port: 443

# retries and delay to check appliance availability
# Override at runtime for docker environment to let the container get healthy
first_steps_retries: 0
first_steps_delay: 5

# LMI FIPS options
# Override this setting if you do not want FIPS mode to be turned on
FIPS_cfg:
  fipsEnabled: false
  tlsv10Enabled: false
  tlsv11Enabled: false

# increase wait time for command execution after appliance restarts (e.g. when FIPS mode is activated) 
ansible_command_timeout: 120
