---

- name: Get the certificate databases
  ibm.isam.isam:
    log: "{{ log_level | default('INFO') }}"
    force: "{{ force | default(False) }}"
    action: ibmsecurity.isam.base.ssl_certificates.certificate_databases.get_all
  register: ret_obj

- name: set a fact to be used by other components
  set_fact:
    get_certificate_databases_ret_obj: "{{ ret_obj['data'] }}"
